### ISSUE TITLE
Configure Jason to parse keys as atoms by default for Phoenix 

### ISSUE THREAD

**Issue by VladislavNekto** [michalmuskala/jason#165]
How to do this

**Comment by michalmuskala** [comment]
@dennym pretty much covered it. An alternative could be to make a wrapper module around `Jason` that passes the required options and use that, rather than `Jason` directly. But yes, there's no global option to do this.

For the future - please use the elixir forum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you.
