### ISSUE TITLE
Cant Serialize list with one element

### ISSUE THREAD

**Issue by JeancarloBarrios** [michalmuskala/jason#27]
Hey Whenever I try to serialize a list of one element it gives me that output:
  `Jason.decode("[39]")`
  `{:ok, '\''}`

If the list has more than one element then i get the correct list.
`Jason.decode("[39, 1]")`
  `{:ok, [39, 1]}`

And Finally if i encode it with Json and then decoded i get the same problem.
  `{:ok, l} = Jason.encode([39])`
 `{:ok, "[39]"}`
 `Jason.decode(l) `
 `{:ok, '\''}`

Does anyone have an idea how I can fix this
  
  
`

**Comment by sorentwo** [comment]
What you're seeing is a character list. If the integers in the list map to ascii characters they'll show up as the characters. The numbers 1-6 show up as themselves because they are out of range. If you were to decode a list like `"[39, 40, 41]"` you would get `'\'()'` instead.

Everything is working, it is just a quirk of how character lists work.
