### ISSUE TITLE
Decode line-delimited JSON

### ISSUE THREAD

**Issue by tsutsu** [michalmuskala/jason#34]
`JSONL` documents, ala http://jsonlines.org, are streams of valid JSON documents, separated by newlines (`"\n"`).

I know it's pretty easy to parse these in Elixir itself (e.g. `StringIO.open(jsonl) |> elem(1) |> IO.binstream(:line) |> Stream.map(&Jason.decode!/1)`), but a convenience method would be nice.

As well, there _may_ be an appreciable amount of redundant work done by the above approach, compared to having Jason manage document-splitting while parsing. Embedding the logic for handling top-level newline tokens in the document _may_ be quite a lot faster. Something to benchmark!

**Comment by michalmuskala** [comment]
I think this could be also solved with something like:

```elixir
jsonl
|> String.splitter("\n")
|> Stream.map(&Jason.decode!/1)
...
```

In general, I would say this is a subset of issue https://github.com/michalmuskala/jason/issues/25 - in here it's easy to do this manually, though, because the separator is a newline and newlines are not allowed inside JSON directly. I'll close this in favour of #25.
