### ISSUE TITLE
How to convert struct from others without side effect?

### ISSUE THREAD

**Issue by chulkilee** [michalmuskala/jason#45]
If an application defines protocol for another application's struct, then does it introduce side-effect - impacting other applications?

```elixir
# application Foo
module Foo.Hello do
  require Protocol
  Protocol.derive(Jason.Encoder, Plug.Upload)
end

# in the same application
module Foo.World do
end

# another application wants to use different encoding behavior
module Bar.Hello do
end
```

Ideally, it would be nice to specify how to convert them when calling `Jason.encode/1`.

Or... at least it would be nice if the change is only applied to the application where it's made.

**Comment by michalmuskala** [comment]
Protocols are global. There's no way around it. If we adopt the DDD language, I'd say that's why I generally wouldn't recommend it as a good way to encode entities - you often want to vary how they are encoded. On the other hand, it's perfectly fine to encode value objects (like a datetime struct or a decimal value) - you rarely, if ever, want to change their representation.

My preferred way to do scoped rendering is with an approach similar to what Phoenix uses with views - an explicit step between "raw" entities and encoded responses.
