### ISSUE TITLE
Support an option to decode a __struct__ element as an atom.

### ISSUE THREAD

**Issue by ghost** [michalmuskala/jason#51]
The `__struct__` element is special in Elixir for marking a map which has only atoms as keys as being a struct. The user should have the option of telling Jason to save the struct element in the JSON as a string (which can be done with tagging required fields) but also should decode the JSON key/value pair` "__struct__": "MyModule"` as `%{__struct__: MyModule` with a value that is an atom using string_to_atom. This would give the user the option to simply pass along the struct element and then decode instead of having to laboriously go through the JSON changing all the maps read. This will make Jason extremely useful with document oriented databases where the JSON is being saved and read frequently.

**Comment by kraythen** [comment]
I could work on a pull request if I know that the repo is being maintained.

**Comment by michalmuskala** [comment]
This repo is being maintained, I'm just not sure about the feature. I don't think it would be enough to just decode the `__struct__` key. One issue is that it would bypass some of the features of structs - like structs always having certain keys or the `@enforce_keys` feature.

**Comment by kraythen** [comment]
Certainly you would be deciding at that point that you trust the JSON to have implemented the struct properly. A possible alternative is to create the struct without just encoding the __struct__ element but that could get much more complicated. What I am trying to avoid is to have to deserialize JSON and then go back through the JSON adding the __struct__ element at every stage of my JSON which has multiple levels and dozens of structs. When I read it from my document database I need to have it become a struct again, not a map. Hence the reason this should be an option, not default behavior. What I dont know is how all the encoders and macros work so it would be longer for me to emplement this but I am willing to give it a try because I need it professionally.

**Comment by OvermindDL1** [comment]
Personally I'm -1 on this, that seems like the job of some higher DSEL on top of Jason (there are some generic ones that do this already) or so for serialization purposes, not for a low-level and fast json library.

**Comment by michalmuskala** [comment]
I'm going to close this. Coercing decoded data into structs probably belongs in some higher-level data transformation/validation/coercion library and not in the low-level JSON encoder.
