### ISSUE TITLE
Define custom encoder for Date

### ISSUE THREAD

**Issue by capablemonkey** [michalmuskala/jason#65]
With Poison, I'm able to define a custom encoder for `Date` by doing the following:

```exs
defimpl Poison.Encoder, for: Date do
  def encode(date, options) do
    Blah.CustomDateFormatter.render_date(date)
    |> Poison.Encoder.encode(options)
  end
end
```

I have a custom encoder because `Date.to_iso8601` [doesn't support](https://github.com/elixir-lang/elixir/issues/8368) years > 9999, so we need to catch this case and encode the Date in a different manner.

When I try to do the same thing with Jason, it doesn't seem to work.  It seems this is because `Jason.Encode` [already defines what to do](https://github.com/michalmuskala/jason/blob/cb1f26a8b3ca7efd4c79437b803cd8021c57d204/lib/encode.ex#L230) with `Date` (also [see this comment](https://github.com/michalmuskala/jason/blob/master/lib/encoder.ex#L151)).

```exs
  defimpl Jason.Encoder, for: Date do
    def encode(value, _opts) do
      "foo!"
    end
  end
```

Is there any way to specify a custom encoding for `Date`?   

After noticing how fast Jason was compared to Poison, I'd love to use it!  This is the only thing holding us back, unfortunately.

**Comment by ImmaculatePine** [comment]
Any updates since then?

**Comment by michalmuskala** [comment]
Overriding protocol implementations is unfortunately not supported in Elixir. Writing an additional implementation as in the example for the poison encoder works mostly accidentally and would for example cause a build failure when constructing a release. A mechanism for overriding protocol implementations should be provided at the Elixir level, this is not something we'll be able to solve in this library.

A solution I'd propose, until protocol overriding becomes part of Elixir (if it does), would be to define a "wrapper" struct around the `Date` values and provide the encoder for it.

Additionally `Date.to_iso8601` since Elixir 1.8 supports rendering dates with year over 9999, so the immediate issue seems to be solved at origin.

**Comment by x-ji** [comment]
We also need this functionality since we need to call `Date.to_iso8601(date, :basic)` instead of the default, which is `Date.to_iso8601(date, :extended)` (the output needs to be `YYYYMMDD` instead of `YYYY-MM-DD`). Currently we can only have a hacky solution, which is to replace the dates in the struct manually, before calling `Jason.encode!`. This seems to be the easiest solution for now.

It would be nice for Elixir to support overriding protocol implementations.

**Comment by x-ji** [comment]
EDIT: Seems that the right solution in my case would be to go with an Ecto custom type. Still, this would be nice to have.
