### ISSUE TITLE
Preserve keys order for signature purpose (option)

### ISSUE THREAD

**Issue by StephaneRob** [michalmuskala/jason#79]
We recently moved from `Poison` to `Jason`, we changed Cloudfront signer with:

```elixir
Jason.encode!(
  %{
    "Statement" => [
      %{
        "Resource" => url,
        "Condition" => %{
          "DateLessThan" => %{
            "AWS:EpochTime" => expires
          }
        }
      }
    ]
  }
)
```

With `Poison` the order is preserved, after the switch to `Jason`, `Resource` and `Condition` are reversed, which lead to an Access denied when we try to access the resource due to an invalid signature.

Do you think an option to preserve the order could be useful ?

**Comment by michalmuskala** [comment]
The fact that Poison preserves order is entirely accidental in here - in general it doesn't and that is because of the fact that maps in Elixir don't preserve order.
For example, if you switch around the `Resource` and `Condition` keys in the code, Poison produces exactly the same output:
```elixir
iex(5)> Poison.encode!(%{"Statement" => [%{
      "Condition" => %{"DateLessThan" => %{"AWS:EpochTime" => expires}}, 
      "Resource" => url
    }]})
"{\"Statement\":[{\"Resource\":\"abc\",\"Condition\":{\"DateLessThan\":{\"AWS:EpochTime\":1}}}]}"
```

Poison encodes map in reverse natural order of maps and Jason encodes them in the natural order, so the order appears reversed.

Fortunately, Jason has tools to deal with it. If the keys are static, you can use the `Jason.Helpers.json_map` macros - they will additionally speed up the encoding. Alternatively you can implement a custom ordered key-value data structure and use the `Jason.Encode.keyword` helper in the encoder protocol implementation. An example solution with `json_map` could look like this:
```elixir
import Jason.Helpers
Jason.encode!(
  json_map(
    Statement: [
      json_map(
        Resource: url,
        Condition: json_map(DateLessThan: json_map("AWS:EpochTime": expires))
      )
    ]
  )
)
```

**Comment by StephaneRob** [comment]
@michalmuskala Thanks for your reply and the example with `json_map` !

Actually It's what I thought about the behaviour of Poison vs Jason. It's why I preferred build my json directly with a string (no order issue anymore).

```elixir
~s({"Statement":[{"Resource":"#{url}","Condition":{"DateLessThan":{"AWS:EpochTime":#{expires}}}}]})
```

**Comment by christopherlai** [comment]
@michalmuskala Thank you for the awesome work on `Jason`.

I was curious when a new release of `Jason` will be available with `Jason.Encode.keyword` included? I see that it's on `master`, but it's not part of the `1.1.2` release.
