### ISSUE TITLE
valid json decode error

### ISSUE THREAD

**Issue by mydearxym** [michalmuskala/jason#88]
hi there ~

got error when i decode a value with `()`

```bash
iex(2)> Jason.decode!(~S({"text": "(or more complex structure)"}))
...(2)>
```

**Comment by OvermindDL1** [comment]
Really?  `Jason.decode!(~S[{"text": "(or more complex structure)"}])` works just fine here.

Note that in your specific example your string closing character is `)`, yet you have a `)` inside it, so then you start a string with `"`, so it gets parsed as:
```
# Jason.decode!(~S({"text": "(or more complex structure)"}))
Jason.decode!("{\"text\": \"(or more complex structure""}))
```
Which as you see leaves an open `"` on the end of the line, waiting for you to type the rest.

As for Jason, I'm not seeing any error with Jason and `()` values?
```
iex> Jason.decode!(~S[{"text": "(or more complex structure)"}])
%{"text" => "(or more complex structure)"}
```

**Comment by michalmuskala** [comment]
This is the issue with the use of the `~S` syntax. If `(` is used as a delimiter, the closing delimiter `)` must be escaped inside the string:
```elixir
Jason.decode!(~S({"text": "(or more complex structure\)"}))
```
Otherwise, the parser treats the quote following the `)` as opening of another string and that's why it waits for further input (since that string is never closed).
